### ISSUE TITLE
LIBUSB_ERROR_IO

### ISSUE THREAD

**Issue by q-depot** [makenai/node-uvc-control#27]
Hi,

I'm using the uvc control in a nodejs app on a raspberry pi, it seems I can open the device but when I try to get a parameter I get LIBUSB_ERROR_IO.

**Comment by positlabs** [comment]
I know it's been almost a year since you asked this, but I finally dusted off my 5 year old pi and got the lib to work. By default, the pi user doesn't have usb access, so you can either run at root (sudo), or add a udev rule as described on [this SO answer](https://askubuntu.com/questions/978552/how-do-i-make-libusb-work-as-non-root)
